# pandas
- 데이터프레임(DataFrame)을 사용하기 위한 패키지
- 데이터프레임은 2차원 테이블 구조로 "액셀"과 같은 용도로 사용된다
- (참고) 1차원의 데이터를 다루기 위해서는 리스트가 사용된다
- copy()

## 데이터 프레임 생성 방법
- 딕셔너리로부터 만드는 방법
- 배열, 리스트, 튜플로부터 만드는 방법
- csv 파일을 읽어 만드는 방법
- 액셀 파일을 읽어 만드는 방법

## import

In [59]:
import pandas as pd

# 레티나 디스플레이를 사용하는 경우 설정
%config InlineBackend.figure_format = 'retina'

In [60]:
## 딕셔너리에서 데이터프레임을 만드는 예

x = {'city': ['서울', '부산', '대구', '대전', '광주'],
     'population': [990, 350, 250, 154, 150],
     'temp': [17, 18, 18, 19, 20]}

df = pd.DataFrame(x)
df

  city  population  temp
0   서울         990    17
1   부산         350    18
2   대구         250    18
3   대전         154    19
4   광주         150    20

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        5 non-null      object
 1   population  5 non-null      int64
 2   temp        5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

- 딕셔너리의 키를 컬럼명으로, 값을 데이터로 사용한다
- 인덱스(행 번호)가 자동으로 만들어진다

In [62]:
## 데이터프레임의 구조(shape)와 행과 열의 수 확인하기

print(df.shape)    # 데이터프레임 구조
print(df.shape[0]) # 행의 수
print(df.shape[1]) # 열의 수

(5, 3)
5
3

# 데이터프레임 다루기

In [64]:
## 일부 컬럼만 보기

df2 = df[['city', 'temp']]
df2

  city  temp
0   서울    17
1   부산    18
2   대구    18
3   대전    19
4   광주    20

# 데이터프레임 저장
- to_csv(): csv 파일로 저장
- to_excel(): 액셀 파일로 저장
- 한글이 깨지는 경우 encoding='utf-8', 'cp949','euc-kr' 등의 옵션 사용
- [한글보기 블로그](https://teddylee777.github.io/pandas/%EA%B3%B5%EA%B3%B5%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%95%9C%EA%B8%80%EA%B9%A8%EC%A7%90%ED%98%84%EC%83%81-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95)

In [65]:
## 데이터프레임을 csv 파일, 액셀로 저장하기

df.to_csv('cities.csv')
df.to_excel('cities.xlsx')

# 파일을 읽고 화면에 출력하기
with open('cities.csv', encoding='utf-8') as f:
    print(f.read())

,city,population,temp
0,서울,990,17
1,부산,350,18
2,대구,250,18
3,대전,154,19
4,광주,150,20

In [66]:
## 데이터프레임 저장시 인덱스 제거하기

df.to_csv('cities.csv', index=False)
df.to_excel('cities.xlsx', index=False)

with open('cities.csv', encoding='utf-8') as f:
    print(f.read())

city,population,temp
서울,990,17
부산,350,18
대구,250,18
대전,154,19
광주,150,20

## 파일을 읽어 데이터프레임 만들기
- read_csv(): csv 파일을 데이터프레임으로 읽기
- read_excel(): 액셀, xlsx 파일을 데이터프레임으로 읽기

In [67]:
## csv 파일을 읽어서 데이터프레임 만들기

df2 = pd.read_csv('cities.csv')  
df2

  city  population  temp
0   서울         990    17
1   부산         350    18
2   대구         250    18
3   대전         154    19
4   광주         150    20

In [68]:
# 액셀 읽기

df3 = pd.read_excel('cities.xlsx')  
df3

  city  population  temp
0   서울         990    17
1   부산         350    18
2   대구         250    18
3   대전         154    19
4   광주         150    20